// Curated from the supplied Pola-version alumni directory, September 2026.
// All 37 distinct bolded names are included, plus seven selected public figures.
// Dates/roles describe the issues recorded in that directory, not graduation
// years or exhaustive tenures. Contributors are not necessarily student alumni.
// Public biographies are linked below. Never copy contact or outreach columns.
const alumniDirectory = [
  {name:'Robert Kagan',sortName:'Kagan, Robert',field:'public-service',role:'Editor-in-Chief',years:'1979',selection:'bold',pages:[1],bio:'Foreign-policy historian and author of The World America Made.',source:'https://www.brookings.edu/people/robert-kagan/'},
  {name:'Eric Edelman',sortName:'Edelman, Eric',field:'public-service',role:'Associate Editor',years:'1979',selection:'bold',pages:[1],bio:'Diplomat who served as U.S. ambassador to Turkey and under secretary of defense for policy.',source:'https://www.merrillcenter.sais-jhu.edu/people-eric-edelman'},
  {name:'Mark Lilla',aliases:['Mark T. Lilla'],sortName:'Lilla, Mark',field:'scholarship',role:'Writer / Director',years:'1980–1981',selection:'bold',pages:[2],bio:'Intellectual historian and author whose work explores political and religious thought.',source:'https://history.columbia.edu/person/lilla-mark-o/'},
  {name:'Edward Lazarus',aliases:['Eddie Lazarus'],sortName:'Lazarus, Edward',field:'advocacy',role:'Senior Editor',years:'1981',selection:'bold',pages:[2],bio:'Attorney, business executive, and author of Closed Chambers, a history of the modern Supreme Court.',source:'https://investors.sonos.com/news-and-events/investor-news/latest-news/2018/Eddie-Lazarus-joins-Sonos-as-Chief-Legal-Officer/default.aspx'},
  {name:'Edward B. Foley',aliases:['Ned Foley','Edward Foley'],sortName:'Foley, Edward',field:'scholarship',role:'Assistant Editor',years:'1981',selection:'bold',pages:[2],bio:'Law professor and former Ohio state solicitor.',source:'https://www.ali.org/profile/4986'},
  {name:'Daniel Patrick Moynihan',sortName:'Moynihan, Daniel Patrick',field:'public-service',role:'Writer',years:'1981',selection:'bold',pages:[2],bio:'U.S. senator from New York, diplomat, and social scientist.',source:'https://www.senate.gov/senators/FeaturedBios/Featured_Bio_MoynihanDP.htm'},
  // Year and biography link updated from the user's September 2026 correction.
  {name:'Michael Froomkin',aliases:['A. Michael Froomkin'],sortName:'Froomkin, Michael',field:'scholarship',role:'Editor-in-Chief',years:'1982',selection:'bold',pages:[2],bio:'Legal scholar and professor at the University of Miami School of Law.',source:'https://en.wikipedia.org/wiki/Michael_Froomkin'},
  {name:'Gideon Rose',sortName:'Rose, Gideon',field:'journalism',role:'Business Staff / Editor-in-Chief',years:'1981–1982; 1984',selection:'bold',pages:[3],bio:'Former editor of Foreign Affairs and author of How Wars End.',source:'https://www.cfr.org/experts/gideon-rose?page=1'},
  {name:'Richard Brookhiser',sortName:'Brookhiser, Richard',field:'journalism',role:'Writer',years:'1981',selection:'bold',pages:[3],bio:'Journalist, historian, and biographer of America’s founding generation.',source:'https://www.simonandschuster.com/authors/Richard-Brookhiser/1055218'},
  {name:'Jonathan Rauch',sortName:'Rauch, Jonathan',field:'journalism',role:'Senior Editor',years:'1982',selection:'bold',pages:[3],bio:'National Magazine Award-winning writer and author of The Constitution of Knowledge.',source:'https://www.brookings.edu/people/jonathan-rauch/'},
  {name:'Fareed Zakaria',sortName:'Zakaria, Fareed',field:'journalism',role:'Writer',years:'1985',selection:'bold',pages:[4],bio:'Host of CNN’s Fareed Zakaria GPS and author of books on democracy and world affairs.',source:'https://fareedzakaria.com/about'},
  {name:'Frederick Kagan',aliases:['Frederick W. Kagan'],sortName:'Kagan, Frederick',field:'public-service',role:'Editor / Executive Editor',years:'1989',selection:'bold',pages:[4],bio:'Military historian and national-security scholar associated with the Critical Threats Project.',source:'https://affordingdefense.aei.org/author/frederick-w-kagan/'},
  {name:'Dale Carpenter',sortName:'Carpenter, Dale',field:'scholarship',role:'Writer',years:'1989',selection:'bold',pages:[4],bio:'Constitutional-law scholar and author of Flagrant Conduct, on the landmark case Lawrence v. Texas.',source:'https://www.smu.edu/law/news-events/2021/~/link.aspx?_id=7BAEBEEA89F6418BA2DD80BC5B816A1D&_z=z'},
  {name:'Andrew Sullivan',sortName:'Sullivan, Andrew',field:'journalism',role:'Writer',years:'1990–1992',selection:'bold',pages:[4],bio:'Political essayist and founding editor of The Daily Dish.',source:'https://www.simonandschuster.com/authors/Andrew-Sullivan/2115018533'},
  {name:'Marc Howard',aliases:['Marc M. Howard','Marc Morjé Howard'],sortName:'Howard, Marc',field:'scholarship',role:'Writer',years:'1991',selection:'bold',pages:[5],bio:'Scholar of democracy and prison reform; founding director of Georgetown’s Prisons and Justice Initiative.',source:'https://prisonsandjustice.georgetown.edu/director/'},
  {name:'Vaughan Turekian',sortName:'Turekian, Vaughan',field:'public-service',role:'Business Associate',years:'1991',selection:'bold',pages:[6],bio:'Science-diplomacy leader and former science and technology adviser to the U.S. secretary of state.',source:'https://sites.nationalacademies.org/PGA/PGA_186934'},
  {name:'Donald Kagan',sortName:'Kagan, Donald',field:'scholarship',role:'Writer',years:'1992',selection:'bold',pages:[6],bio:'Yale historian of ancient Greece, known for his four-volume history of the Peloponnesian War.',source:'https://news.yale.edu/2021/08/10/donald-kagan-celebrated-historian-ancient-world-and-revered-teacher'},
  {name:'Kimberly Kagan',sortName:'Kagan, Kimberly',field:'public-service',role:'Writer',years:'1994',selection:'bold',pages:[6],bio:'Military historian and founder of the Institute for the Study of War.',source:'https://understandingwar.org/people/kimberly-kagan/'},
  {name:'Brendan Koerner',aliases:['Brendan I. Koerner'],sortName:'Koerner, Brendan',field:'journalism',role:'Writer',years:'1996',selection:'bold',pages:[7],bio:'WIRED contributing editor and author of The Skies Belong to Us.',source:'https://www.wired.com/author/brendan-i-koerner/'},
  {name:'Josh Chafetz',sortName:'Chafetz, Josh',field:'scholarship',role:'Writer / General Manager',years:'1997–1998',selection:'bold',pages:[8],bio:'Legal scholar of Congress, constitutional law, and the separation of powers.',source:'https://www.law.georgetown.edu/faculty/josh-chafetz/'},
  {name:'Peter van Agtmael',aliases:['Peter J. van Agtmael'],sortName:'van Agtmael, Peter',field:'journalism',role:'International Affairs Editor',years:'2001',selection:'bold',pages:[10],bio:'Magnum photographer whose work examines war, memory, and American society.',source:'https://store.magnumphotos.com/collections/peter-van-agtmael'},
  {name:'Jowei Chen',sortName:'Chen, Jowei',field:'scholarship',role:'Writer',years:'2001',selection:'bold',pages:[10],bio:'Political scientist studying redistricting, political geography, and representation.',source:'https://prod.lsa.umich.edu/polisci/people/faculty/jowei.html'},
  {name:'Jacob Leibenluft',sortName:'Leibenluft, Jacob',field:'public-service',role:'Writer / International Editor',years:'2002–2004',selection:'bold',pages:[11],bio:'Economic-policy official named the U.S. Treasury’s inaugural chief recovery officer in 2021.',source:'https://home.treasury.gov/news/press-releases/jy0121'},
  {name:'Carl Gershman',sortName:'Gershman, Carl',field:'advocacy',role:'Writer',years:'2003',selection:'bold',pages:[12],bio:'Founding president of the National Endowment for Democracy.',source:'https://www.ned.org/carl-gershman/'},
  {name:'Oona Hathaway',aliases:['Oona A. Hathaway'],sortName:'Hathaway, Oona',field:'scholarship',role:'Writer',years:'2003',selection:'bold',pages:[13],bio:'International-law scholar at Yale and co-author of The Internationalists.',source:'https://law.yale.edu/oona-hathaway'},
  {name:'Jim Sleeper',sortName:'Sleeper, Jim',field:'journalism',role:'Writer',years:'2004–2014',selection:'bold',pages:[14],bio:'Writer on American civic culture and politics, and former Yale political-science lecturer.',source:'https://www.jimsleeper.com/?page_id=5'},
  {name:'Ivo H. Daalder',sortName:'Daalder, Ivo',field:'public-service',role:'Writer',years:'2005',selection:'bold',pages:[16],bio:'Foreign-policy scholar and former U.S. ambassador to NATO.',source:'https://globalaffairs.org/research/experts/ivo-h-daalder'},
  {name:'Joseph S. Nye Jr.',sortName:'Nye, Joseph',field:'scholarship',role:'Writer',years:'2005',selection:'bold',pages:[16],bio:'International-relations scholar who developed the concept of soft power; former Harvard Kennedy School dean.',source:'https://www.hks.harvard.edu/index.php/faculty-research/policy-topics/international-relations-security/joseph-nye-obituary'},
  {name:'Maggie Goodlander',aliases:['Margaret Goodlander','Margaret (Maggie) Goodlander'],sortName:'Goodlander, Maggie',field:'public-service',role:'Associate Editor / Features Editor / Editor-in-Chief',years:'2006–2008',selection:'bold',pages:[17],bio:'Elected to Congress from New Hampshire in 2024 after service in the Navy Reserve and Justice Department.',source:'https://goodlander.house.gov/meet-maggie/'},
  {name:'Cyrus Habib',sortName:'Habib, Cyrus',field:'public-service',role:'Writer',years:'2008',selection:'bold',pages:[19],bio:'Former lieutenant governor of Washington who entered the Society of Jesus in 2020.',source:'https://www.jesuits.org/stories/meet-the-lieutenant-governor-who-quit-politics-to-become-a-jesuit-with-cyrus-habib-sj/'},
  {name:'Edward Fishman',aliases:['Eddie Fishman'],sortName:'Fishman, Edward',field:'public-service',role:'International Section / Editor-in-Chief',years:'2008–2010',selection:'bold',pages:[20,22],bio:'Economic-statecraft expert and author of Chokepoints: American Power in the Age of Economic Warfare.',source:'https://www.cfr.org/experts/edward-fishman'},
  {name:'Stephen Sestanovich',sortName:'Sestanovich, Stephen',field:'public-service',role:'Writer',years:'2009',selection:'bold',pages:[21],bio:'Russia specialist and former U.S. ambassador-at-large for the former Soviet Union.',source:'https://www.cfr.org/experts/stephen-sestanovich'},
  {name:'John Yoo',sortName:'Yoo, John',field:'scholarship',role:'Writer',years:'2010',selection:'bold',pages:[23],bio:'Berkeley law professor whose scholarship addresses constitutional law, executive power, and national security.',source:'https://www.law.berkeley.edu/our-faculty/faculty-profiles/john-yoo/'},
  {name:'Peter W. Singer',aliases:['Peter Warren Singer'],sortName:'Singer, Peter',field:'public-service',role:'Writer',years:'2010',selection:'bold',pages:[23],bio:'Strategist and author studying warfare, cybersecurity, and emerging technology.',source:'https://www.newamerica.org/people/peter-warren-singer/'},
  {name:'Jordan Schneider',sortName:'Schneider, Jordan',field:'journalism',role:'Feature Editor',years:'2011',selection:'bold',pages:[23],bio:'Founder of the ChinaTalk podcast and newsletter on China, technology, and international affairs.',source:'https://www.cnas.org/people/jordan-schneider'},
  {name:'Noah Remnick',sortName:'Remnick, Noah',field:'journalism',role:'Writer / Director of PR / Editor-in-Chief',years:'2011–2012',selection:'bold',pages:[24,25],bio:'Journalist and Rhodes Scholar whose reporting for The New York Times examined public health and policing.',source:'https://history.yale.edu/news/former-history-major-noah-remnick-was-chosen-rhodes-scholar?page=1'},
  {name:'Anna-Sophie Harling',sortName:'Harling, Anna-Sophie',field:'advocacy',role:'Photo / Associate Editor',years:'2013',selection:'bold',pages:[27],bio:'Online-safety specialist and former European managing director at NewsGuard.',source:'https://www.turing.ac.uk/people/guest-speakers/anna-sophie-harling'},
  {name:'Jessica Neuwirth',sortName:'Neuwirth, Jessica',field:'advocacy',role:'Editorial Staff',years:'1980',selection:'additional',pages:[1],bio:'Human-rights lawyer and co-founder of Equality Now, advocating for women’s legal equality.',source:'https://equalitynow.org/staff-member/jessica-neuwirth-usa/'},
  {name:'Kevin Delaney',sortName:'Delaney, Kevin',field:'journalism',role:'Associate Editor',years:'1991–1992',selection:'additional',pages:[5],bio:'Journalist and co-founder of Quartz and Charter.',source:'https://www.charterworks.com/about-page-who-we-are/'},
  {name:'Chris Mooney',sortName:'Mooney, Chris',field:'journalism',role:'Writer',years:'1998',selection:'additional',pages:[8],bio:'Science and environment journalist who has reported for The Washington Post and Mother Jones.',source:'https://www.washingtonpost.com/people/chris-mooney/?itid=ai_author_bar_component_mooneyc'},
  {name:'Brian Wallach',aliases:['Brian S. Wallach'],sortName:'Wallach, Brian',field:'advocacy',role:'Editor-in-Chief',years:'2001',selection:'additional',pages:[9],bio:'Co-founder of I AM ALS and advocate for ALS research and patient support.',source:'https://www.iamals.org/members/brian-wallach/'},
  {name:'Eliana Johnson',sortName:'Johnson, Eliana',field:'journalism',role:'Writer',years:'2003',selection:'additional',pages:[12],bio:'Political journalist and Washington Free Beacon editor, previously a White House correspondent for POLITICO.',source:'https://freebeacon.com/author/eliana-johnson/'},
  {name:'James Kirchick',sortName:'Kirchick, James',field:'journalism',role:'Writer',years:'2005',selection:'additional',pages:[17],bio:'Journalist and author of Secret City: The Hidden History of Gay Washington.',source:'https://jameskirchick.com/about/'},
  {name:'Suzanne Nossel',sortName:'Nossel, Suzanne',field:'advocacy',role:'Writer',years:'2005',selection:'additional',pages:[16],bio:'Free-expression advocate, former PEN America CEO, and author of Dare to Speak.',source:'https://pen.org/profile/suzanne-nossel/'}
];
const alumniFields = [
  ['journalism','Journalism & Media'],
  ['public-service','Public Service & Policy'],
  ['scholarship','Law & Scholarship'],
  ['advocacy','Business & Advocacy']
];

// Alumni shown first on the alumni page and on the history page, most prominent first.
// Each `name` must match an entry above. Portraits come from Wikimedia Commons under free
// licences; the page shows the credit, so keep `credit`, `license`, and `creditUrl` accurate
// when replacing a photo (480×600 WebP in dist/assets/alumni/).
const alumniFeatured = [
  {name:'Fareed Zakaria',photo:'/assets/alumni/fareed-zakaria.webp',credit:'Anders Krusberg / Peabody Awards',license:'CC BY 2.0 (cropped)',creditUrl:'https://commons.wikimedia.org/wiki/File:Fareed_Zakaria,_Peabody_Awards_(2012)_(cropped).jpg'},
  {name:'Daniel Patrick Moynihan',photo:'/assets/alumni/daniel-patrick-moynihan.webp',credit:'John Mathew Smith & www.celebrity-photos.com',license:'CC BY-SA 2.0 (cropped)',creditUrl:'https://commons.wikimedia.org/wiki/File:Patrick_Moynihan_1998_(cropped).jpg'},
  {name:'Robert Kagan',photo:'/assets/alumni/robert-kagan.webp',credit:'Mariusz Kubik',license:'CC BY 3.0 (cropped)',creditUrl:'https://commons.wikimedia.org/wiki/File:Robert_Kagan_Fot_Mariusz_Kubik_03.jpg'},
  {name:'Joseph S. Nye Jr.',photo:'/assets/alumni/joseph-nye.webp',credit:'Scott Davis / U.S. Department of Defense',license:'Public domain',creditUrl:'https://commons.wikimedia.org/wiki/File:Portrait_of_Dr._Joseph_S._Nye,_Jr.,_Assistant_Secretary_of_Defense,_International_Security_Affairs.jpg'},
  {name:'Gideon Rose',photo:'/assets/alumni/gideon-rose.webp',credit:'Halifax International Security Forum',license:'CC BY-SA 2.0 (cropped)',creditUrl:'https://commons.wikimedia.org/wiki/File:Gideon_Rose.jpg'},
  {name:'Maggie Goodlander',photo:'/assets/alumni/maggie-goodlander.webp',credit:'Nate Payne / U.S. House of Representatives',license:'Public domain',creditUrl:'https://commons.wikimedia.org/wiki/File:Maggie_Goodlander_official_portrait,_119th_Congress.jpg'},
  {name:'Oona Hathaway',photo:'/assets/alumni/oona-hathaway.webp',credit:'Wikimedia Commons',license:'CC0',creditUrl:'https://commons.wikimedia.org/wiki/File:Oona_Hathaway_Headshot.jpg'},
  {name:'Jonathan Rauch',photo:'/assets/alumni/jonathan-rauch.webp',credit:'New America',license:'CC BY 2.0 (cropped)',creditUrl:'https://commons.wikimedia.org/wiki/File:Jonathan_Rauch,_2013_(cropped).jpg'}
];
